[project]
name = 'Creator-Tipping'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.creator_tipping]
path = 'contracts/creator_tipping.clar'
clarity_version = 2
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lint_groups]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
